apiVersion: v1
kind: Secret
metadata:
  name: postgres-gitea-app
  namespace: mercato-sandboxes
  labels:
    app.kubernetes.io/part-of: mercato-sandboxes
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: REPLACE_ME_GITEA_DB_PASSWORD
