apiVersion: v1
kind: Secret
metadata:
  name: postgres-coder-app
  namespace: mercato-sandboxes
  labels:
    app.kubernetes.io/part-of: mercato-sandboxes
type: kubernetes.io/basic-auth
stringData:
  username: coder
  password: REPLACE_ME_CODER_DB_PASSWORD
