apiVersion: v1
kind: Secret
metadata:
  name: postgres-onboarding-app
  namespace: mercato-sandboxes
  labels:
    app.kubernetes.io/part-of: mercato-sandboxes
type: kubernetes.io/basic-auth
stringData:
  username: onboarding
  password: REPLACE_ME_ONBOARDING_DB_PASSWORD
