apiVersion: v1
kind: Secret
metadata:
  name: sandbox-lvh-me-tls
  namespace: mercato-sandboxes
type: kubernetes.io/tls
stringData:
  tls.crt: |
    REPLACE_WITH_CERT_PEM
  tls.key: |
    REPLACE_WITH_KEY_PEM
