apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: mercato-sandboxes
  labels:
    app.kubernetes.io/part-of: mercato-sandboxes
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<gh-username>",
          "password": "<gh-token>",
        }
      }
    }
