apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmercato.appSecretName" . }}
  labels:
    {{- include "openmercato.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "openmercato.databaseUrl" . | quote }}
  REDIS_URL: {{ include "openmercato.redisUrl" . | quote }}
  QUEUE_REDIS_URL: {{ include "openmercato.redisUrl" . | quote }}
  CACHE_REDIS_URL: {{ include "openmercato.redisUrl" . | quote }}
  JWT_SECRET: {{ .Values.app.secretEnv.jwtSecret | quote }}
  AUTH_SECRET: {{ .Values.app.secretEnv.authSecret | quote }}
  TENANT_DATA_ENCRYPTION_FALLBACK_KEY: {{ .Values.app.secretEnv.tenantDataEncryptionFallbackKey | quote }}
  OM_INIT_SUPERADMIN_EMAIL: {{ .Values.app.secretEnv.initSuperadminEmail | quote }}
  OM_INIT_SUPERADMIN_PASSWORD: {{ .Values.app.secretEnv.initSuperadminPassword | quote }}
  {{- range $key, $value := .Values.app.secretEnv.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
