apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmercato.postgresSecretName" . }}
  labels:
    {{- include "openmercato.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
