apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openmercato.storageName" . }}
  labels:
    {{- include "openmercato.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.app.storage.accessModes | nindent 4 }}
  {{- with .Values.app.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
