apiVersion: v1
kind: Secret
metadata:
  name: openmercato-app-secrets
  namespace: mercato-sandboxes
  labels:
    app.kubernetes.io/part-of: mercato-sandboxes
type: Opaque
stringData:
  DATABASE_URL: postgres://openmercato:REPLACE_ME_OPENMERCATO_DB_PASSWORD@openmercato-postgres-rw.mercato-sandboxes.svc.cluster.local:5432/openmercato?sslmode=disable
  REDIS_URL: redis://openmercato-redis-rw.mercato-sandboxes.svc.cluster.local:6379
  QUEUE_REDIS_URL: redis://openmercato-redis-rw.mercato-sandboxes.svc.cluster.local:6379
  CACHE_REDIS_URL: redis://openmercato-redis-rw.mercato-sandboxes.svc.cluster.local:6379
  JWT_SECRET: REPLACE_ME_OPENMERCATO_JWT_SECRET
  AUTH_SECRET: REPLACE_ME_OPENMERCATO_AUTH_SECRET
  TENANT_DATA_ENCRYPTION_FALLBACK_KEY: REPLACE_ME_OPENMERCATO_ENCRYPTION_FALLBACK_KEY
  OM_INIT_SUPERADMIN_EMAIL: admin@example.com
  OM_INIT_SUPERADMIN_PASSWORD: REPLACE_ME_OPENMERCATO_ADMIN_PASSWORD
  SANDBOX_BILLING_WEBHOOK_SECRET: REPLACE_ME_OPENMERCATO_BILLING_WEBHOOK_SECRET
  SANDBOX_BILLING_CONTEXT_SECRET: REPLACE_ME_OPENMERCATO_BILLING_CONTEXT_SECRET
  MOCK_GATEWAY_WEBHOOK_SECRET: REPLACE_ME_OPENMERCATO_MOCK_GATEWAY_WEBHOOK_SECRET
